language: ruby
rvm:
  - 2.1.0
before_script:
  - "bundle exec rake test_app"
script: bundle exec rspec spec
notifications:
  email:
    - marek.buszman@netguru.co
branches:
  only:
    - master
    - 2-1-stable
